version: '3.8'

# networks:
#   loginnetwork:
#     driver: bridge

services:
  db:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: gquaaCPma8
      MYSQL_DATABASE: loginapp
    volumes:
      - db_data_login:/var/lib/mysql
    restart: always
    # networks:
    #   - loginnetwork

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
    restart: always
    # networks:
    #   - loginnetwork

volumes:
  db_data_login:
